🔀 add TwyperFlip
theapache64/twyper pull request #3
Opened 2022-02-25 18:37 UTC by yash-k9

Twyper Flip takes in three extra parameters, two composables, one for front and back and modifier for the box. Animations are added in the existing CardController.

```@Composable
inline fun <reified T> TwyperFlip(
    items: List<T>,
    onItemRemoved: (T, SwipedOutDirection) -> Unit,
    onEmpty: () -> Unit = {},
    twyperController: TwyperController = rememberTwyperController(),
    stackCount: Int = 2,
    paddingBetweenCards: Float = 40f,
    modifier: Modifier = Modifier,
    cardModifier: () -> Modifier,
    crossinline front: @Composable (T) -> Unit,
    crossinline back: @Composable (T) -> Unit
) 
```
https://user-images.githubusercontent.com/59912430/155768674-90167ea2-bd04-456f-a5b1-295cf814d920.mp4

2022-02-26 04:49 UTC, theapache64 requested changes

2022-02-26 04:49 UTC, theapache64 commented on sample/src/main/java/com/github/theapache64/twyper/Util.kt
> +    fun randomColor(): Color {
Looks unused. Do we need this method?

2022-02-26 04:49 UTC, theapache64 commented on twyper/src/main/java/com/github/theapache64/twyper/CardController.kt
>      var swipedOutDirection: SwipedOutDirection?
I think this should be inside a separate class. Consider create a new class by subclassing `CardControllerImpl`. The problem is, here we are considering all cards as flippable. But that's not true. Only cards that are inside TwyperFlip is flippable.

2022-02-26 04:49 UTC, theapache64 commented on twyper/src/main/java/com/github/theapache64/twyper/CardController.kt
>  }
Same as above

2022-02-26 04:49 UTC, theapache64 commented on twyper/src/main/java/com/github/theapache64/twyper/CardController.kt
>      }
Consider create a new method. Something like `rememberFlipCardController`

2022-02-26 04:49 UTC, theapache64 commented on twyper/src/main/java/com/github/theapache64/twyper/CardController.kt
> +        private const val FINAL_FLIP_ANGLE = 180f
Same as above. This should be inside `FlipCardController`

2022-02-26 04:49 UTC, theapache64 commented on twyper/src/main/java/com/github/theapache64/twyper/CardController.kt
> +
Same as above.

2022-02-26 04:49 UTC, theapache64 commented on twyper/src/main/java/com/github/theapache64/twyper/CardController.kt
> +
Same as above

2022-02-26 04:49 UTC, theapache64 commented on twyper/src/main/java/com/github/theapache64/twyper/CardController.kt
> +    }
Same as above

2022-02-26 09:23 UTC, yash-k9 commented on sample/src/main/java/com/github/theapache64/twyper/Util.kt
> +    fun randomColor(): Color {
In the Flip version, we are constructing the modifier outside the Composable context, so was not able to use the existing rememberRandomColor() method. Created this method to generate the colors, Shall I modify or place it elsewhere?

2022-02-26 10:00 UTC, theapache64 commented on sample/src/main/java/com/github/theapache64/twyper/Util.kt
> +    fun randomColor(): Color {
I think you can remove this method, and then extract out the color generation logic from the `rememberRandomColor()`. Then you'll be able to use it from both composable and non-composable context.

2022-02-27 07:27 UTC, yash-k9 commented on twyper/src/main/java/com/github/theapache64/twyper/TwyperController.kt
> +
Can I create separate controller for the FlipCard and separate the classes to packages, like cardControllers, TwyperControllers?

2022-02-27 07:27 UTC, yash-k9 commented on twyper/src/main/java/com/github/theapache64/twyper/CardController.kt
>      var swipedOutDirection: SwipedOutDirection?
Yes, Agreed! 👍

2022-02-27 07:27 UTC, yash-k9 commented on sample/src/main/java/com/github/theapache64/twyper/RandomColor.kt
> +       randomColor()
I extracted the color generation logic here, Did I get this right?

2022-03-06 11:31 UTC, theapache64 commented on sample/src/main/java/com/github/theapache64/twyper/RandomColor.kt
> +       randomColor()
Yeah. this is fine.

2022-03-06 11:32 UTC, theapache64 approved these changes

2022-03-06 11:34 UTC, theapache64 commented on twyper/src/main/java/com/github/theapache64/twyper/TwyperController.kt
> +
I think this is fine for now. We'll refactor the code later. I'll raise a separate PR for that later.

2022-03-06 11:34 UTC, merged